
services:
  sqlserver:
    build: ./db
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Songlong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Songlong@123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASS: Songlong@123

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
