FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

# Cài đặt sqlcmd và công cụ
RUN apt-get update && \
    apt-get install -y curl gnupg apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
    ln -s /opt/mssql-tools/bin/* /usr/bin/ && \
    rm -rf /var/lib/apt/lists/*

# Copy script khởi tạo
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER mssql

# Đặt entrypoint
CMD ["/entrypoint.sh"]
